name: loop_page_view
description: A simple Flutter PageView builder constructor wrapper that allows for endless scrolling on both directions.
version: 1.1.0
homepage: https://github.com/wjuniorgit/loop_page_view
repository: https://github.com/wjuniorgit/loop_page_view

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter