name: loop_page_view
description: A simple Flutter PageView builder constructor wrapper that allows for "indefinitely" scrolling on both directions.
version: 1.0.5
homepage: https://github.com/wjuniorgit/loop_page_view
repository: https://github.com/wjuniorgit/loop_page_view

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
