name: loop_page_view
description: A simple PageView that allows for "indefinitely" scrolling.
version: 1.0.0
homepage: https://github.com/wjuniorgit/loop_page_view
repository: https://github.com/wjuniorgit/loop_page_view

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
